version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: telegram
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  